export const T = {
  FIREBASE_GET_PREFECTURE_DATA: 'FIREBASE_GET_PREFECTURE_DATA',
  FIREBASE_GET_CITIES_DATA: 'FIREBASE_GET_CITIES_DATA',
  AJAX_GET_TRANSLATE_CITY: 'AJAX_GET_TRANSLATE_CITY',
  AJAX_GET_WEATHER_DATA: 'AJAX_GET_WEATHER_DATA',
  AJAX_GET_WEATHER_ERROR: 'AJAX_GET_WEATHER_ERROR',
  RESET_ERROR_BOOL: 'RESET_ERROR_BOOL',
  POST_USER_SENSITIVITY_DATA: 'POST_USER_SENSITIVITY_DATA',
  GET_USER_SENSITIVITY_DATA: 'GET_USER_SENSITIVITY_DATA',
  SET_SELECT_PREFECTURE: 'SET_SELECT_PREFECTURE',
  SET_SELECT_STATE_CITY: 'SET_SELECT_STATE_CITY',
  RESET_SELECT_PREFECTURE: 'RESET_SELECT_PREFECTURE',
  SET_SELECT_CITY: 'SET_SELECT_CITY',
  RESET_LOCAL_DATA: 'RESET_LOCAL_DATA'
}
